service: my-test

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 2048
  lambdaHashingVersion: 20201221
  stage: dev
  timeout: 15
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:*
        - cloudformation:*
        - ec2:*
        - events:*
        - iot:*
        - lambda:*
        - rds:*
        - route53:*
        - s3:*
        - sns:*
        - sqs:*
        - tag:*
        - es:*
        - xray:*
        - apigateway:*
        - elasticloadbalancing:*
      Resource: "*"
functions:
  api:
    handler: handler.api
    events:
      - http: ANY /{proxy+}
      - http: ANY /